### ISSUE TITLE
Web portal in laravel source code 

### ISSUE THREAD

**Issue by MassMadankumar** [sunxfancy/flex-bison-examples#1]
Job Listing Panel
 
Web Portal:
1. Registration for "Job Seeker"
    Fields: Name, Email, Phone, Experience (in Years), Notice Period (in Days), Skills, Job Location (Select), Resume, Photo
2. Registration for "Recruiter"
    Fields: Company Name, Email, Phone, Address
3. Login
 
Recruiter Dashboard:
1. "Job Post" - CRUD Operation
Fields: Job Title, Experience, Job Description, Skills Required, Status (Active, Inactive)
 
2. "Find Candidates"
    List the Candidates based on Search Filters
    Search Filters: Skills, Notice Period (<=), Min Experience (>=), Max Experience (<=), Location
 
3. "Applied Jobs"
    List the Applied Candidates
    List Fields:
    Photo, Candidate Name, Experience, Phone, Job Title, Resume (Download Option)
 
 
Job Seeker Dashboard:
1. Find Jobs:
    List the Active Jobs based on Search Filters
    Search Filters: Skills, Company Name, Min Experience (>=), Max Experience (<=), Location
    List of Fields: Job Title, Company Name, Experience
    Actions: Apply for Job [Mail to be Sent to Recruiter about Candidate]
 
Technical Requirements (Use the below and built your application):
Migrations
Seeder (for Location Dropdown and insert 10 Cities)
Middleware
Job (For Mail)
Validators
Relationships
Use Laravel Helper Function Wherever Possible

**Comment by MassMadankumar** [comment]
I want source code for web portal jobseeker and recruiter login in laravel 8

**Comment by sunxfancy** [comment]
Why do you talking about this unrelated topic?
